### PR TITLE
Update the dependencies version

### PR DESCRIPTION
**Pull request by keyuan0701**

### CODE REVIEW

**Review by jianhua-git — COMMENTED** [review]
checked

**Comment by gkl5433** [comment]
good

**Comment by gkl5433** [comment]
good

**Review by xujiangang-git — COMMENTED** [review]
checked

**Review by xueli-hu — COMMENTED** [review]
good

**Review by chunhua-liu — DISMISSED** [review]

**Review by chunhua-liu — APPROVED** [review]

**Pull request merged**
